### ISSUE TITLE
No information on how to contact curators 

### ISSUE THREAD

**Issue by l-tilley** [MfN-Berlin/geocase-infrastructure#1]
Not all the fields are self-evident, and the user does not know how to continue and whom to contact in order to gather more information about the objects. The detail view available originally seems not present anymore or is too well hidden.

From SMNS Stuttgart and NHM Vienna

**Comment by falkogloeckler** [comment]
related to #11

**Comment by falkogloeckler** [comment]
This issue is sufficiently covered by #9 and #11.
Thus, I close this one.
